#!/usr/bin/env python3
"""Render planning documents that contain chapter numbers from toc_data.py.
Usage: python3 tools/build_planning.py   (run from anywhere)
Outputs: planning/11-toc-v2-renumbered.md, 03-dependency-map.md, 12-first-read-path-and-tags.md,
         05-project-plan.md, chapter-map.json
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import toc_data as T
ROOT = os.path.join(os.path.dirname(__file__), "..", "planning")
num = {c[1]: i + 1 for i, c in enumerate(T.C)}
ch = {c[1]: c for c in T.C}
def n(k): return f"Ch {num[k]}"
def title(k): return ch[k][2]
def w(name, text):
    with open(os.path.join(ROOT, name), "w") as f: f.write(text)

# ---------- chapter map
w("chapter-map.json", json.dumps({k: {"number": num[k], "title": ch[k][2], "tag": ch[k][3], "first_read": ch[k][4]} for k in num}, indent=1) + "\n")

# ---------- 11 TOC
L = ["# 11 — Table of Contents v2 (renumbered)", "",
 "**Generated by `tools/build_planning.py` from `tools/toc_data.py`. Do not edit numbers by hand.**",
 f"Total chapters: **{len(T.C)}**. Supersedes `02-table-of-contents-and-curriculum.md` (kept as v1 history; its chapter numbers are obsolete).", "",
 "Tags: **[Core]** = every learner needs it to progress. **[Deep]** = important for mastery, not required on first pass. Path column: ● = on the First-Read Path, ◐ = only the marked sections on the first pass, ○ = later. See `12-first-read-path-and-tags.md`.", "",
 "Every chapter ends with the standard checkpoint: What You Learned · New Vocabulary · Commands Learned · Common Mistakes · Practice (five levels) · Self-Test · Before Moving On. Solutions are separate.", "",
 "## FRONT MATTER",
 "Half title · Title page · Copyright page · Publisher and author information · Edition/version statement · Disclaimer · Trademark and non-affiliation notice · Licensing statement (pending verification) · Dedication · Foreword (placeholder) · Preface (including the author's verification methodology) · How to use this book (Core/Deep tags, First-Read Path, callouts, shells) · Who this is for · Learning roadmap · Prerequisites · Equipment and software · Table of contents.", ""]
sym = {"full": "●", "part": "◐", "later": "○"}
for pi, (pn, pt) in enumerate(T.PARTS):
    L += [f"## PART {pn} — {pt.upper()}", "", "| Ch | Title | Tag | Path | Teaches |", "|---|---|---|---|---|"]
    for c in T.C:
        if c[0] == pi:
            L.append(f"| {num[c[1]]} | {c[2]} | {c[3]} | {sym[c[4]]} | {c[6]} |")
    L.append("")
    for pr in T.PROJECTS:
        if ch[pr[2]][0] == pi:
            L.append(f"- **Project {pr[0]}** ({pr[1]}) follows {n(pr[2])}.")
    L.append("")
L += ["## BACK MATTER", "Appendices · Glossary · Sources and Further Reading · Author biography (placeholder) · SHARIF TECHNOLOGIES publisher section · Final competency checklist · Index.", "", "### Appendices", ""]
L += [f"- **Appendix {a}** — {t}" for a, t in T.APPENDICES]
w("11-toc-v2-renumbered.md", "\n".join(L) + "\n")

# ---------- 03 dependency map
L = ["# 03 — Technical Dependency Map (v2, generated)", "",
 "**Generated from `tools/toc_data.py`; ordering is machine-checked (every prerequisite appears earlier).** Rule: no chapter may use a term or skill not taught earlier, unless defined inline at first use with a pointer forward.", "",
 "| Chapter | Requires |", "|---|---|"]
for c in T.C:
    L.append(f"| {num[c[1]]} {c[2]} | " + (", ".join(f"{num[r]} {title(r)}" for r in c[5]) or "—") + " |")
L += ["", "## Known forward-reference risks (managed deliberately)",
 f"1. {n('model')} previews remotes before {n('remotes')} — a flagged one-paragraph preview.",
 f"2. {n('tracking')} mentions secrets before {n('gitsec')} — brief warning now, full treatment later.",
 f"3. {n('history_view')} uses 'hash' — informal definition first, formal in {n('objects')}.",
 f"4. {n('gitsec')} covers credentials at Git level; GitHub-specific tokens and keys wait for {n('ghauth')}.",
 f"5. {n('readme')} needs Markdown — taught earlier in {n('markdown')}.",
 f"6. {n('tags')} previews GitHub Releases before {n('releases')} — one-line pointer only.",
 f"7. {n('remotes')} teaches remotes with a local bare repository, so it does not depend on any GitHub chapter."]
w("03-dependency-map.md", "\n".join(L) + "\n")

# ---------- 12 first-read path
fr = [c for c in T.C if c[4] == "full"]; pt = [c for c in T.C if c[4] == "part"]; lt = [c for c in T.C if c[4] == "later"]
L = ["# 12 — Core/Deep Tags and the First-Read Path (specification)", "",
 "This document specifies the text for the book's opening 'How to use this book' section and is generated from `tools/toc_data.py`.", "",
 "## Tags", "- **[Core]** — every learner needs this material to progress. If you skip a Core chapter, later chapters may not make sense.",
 "- **[Deep]** — important for mastery, but not needed on a first pass. You can skip a Deep chapter (or Deep sections inside a Core chapter) and come back later; no Core chapter depends on a Deep chapter (machine-checked by the build script).",
 "- Inside chapters, individual sections may carry their own **[Deep]** tag.", "",
 "## Three ways to read",
 "1. **First-Read Path** (● below): the shortest coherent route from no knowledge to using Git and GitHub for real work.",
 "2. **Second pass**: the remaining Core chapters (◐ sections completed, ○ Core chapters).",
 "3. **Mastery pass**: all Deep chapters, then the mastery chapters.", "",
 f"## First-Read Path ({len(fr)} chapters in full)", "", "| Order | Chapter | Tag |", "|---|---|---|"]
for i, c in enumerate(fr, 1): L.append(f"| {i} | {num[c[1]]} {c[2]} | {c[3]} |")
L += ["", f"## Partly read on the first pass ({len(pt)} chapters) — read only the sections marked *First read* inside each", ""]
L += [f"- {num[c[1]]} {c[2]} [{c[3]}]" for c in pt]
L += ["", f"## Later ({len(lt)} chapters)", ""]
L += [f"- {num[c[1]]} {c[2]} [{c[3]}]" for c in lt]
core_dep = [(c[2], r) for c in T.C if c[3] == "Core" for r in c[5] if ch[r][3] == "Deep"]
L += ["", "## Consistency check: Core chapters that require a Deep chapter", "", ("None." if not core_dep else "\n".join(f"- {a} requires Deep {title(b)}" for a, b in core_dep))]
w("12-first-read-path-and-tags.md", "\n".join(L) + "\n")
fr_bad = [(c[2], r) for c in T.C if c[4] == "full" for r in c[5] if ch[r][4] == "later"]
if core_dep or fr_bad:
    print("ERROR core->deep:", core_dep, "first-read->later:", fr_bad); sys.exit(1)

# ---------- 05 project plan
L = ["# 05 — Practical Project Plan, Scenarios and Assessment (v2, generated)", "",
 "Chapter numbers come from `tools/toc_data.py`. Every project has: goal, prerequisites, steps, expected result, checkpoint questions and a reference solution (in `solutions/`). **An exercise or project may not be published until its commands have been run and its expected results recorded** (see `exercises/registry.csv`).", "",
 "## The twelve projects", "", "| # | Project | After | Realistic content | Skills |", "|---|---|---|---|---|"]
for p in T.PROJECTS: L.append(f"| {p[0]} | {p[1]} | {n(p[2])} {title(p[2])} | {p[3]} | {p[4]} |")
L += ["", f"## Capstone ({n('capstone')}, 23 steps)",
 "Create project → init Git → .gitignore → meaningful commits → branches → features → merges → resolve conflict → create GitHub repo → push → Issues → Project → PR → code review → Actions → automated tests → security controls (only features verified for the learner's account type and repository visibility) → release → documentation → prepare for another contributor → simulate production problem → recover from a Git mistake → final professional repository. Reference implementation in `solutions/capstone-reference/`.", "",
 f"## Twelve scenarios ({n('scenarios')})",
 "1 Student's first project · 2 Solo developer builds a website · 3 Two developers collaborate · 4 Team mobile-app development · 5 Company manages production software · 6 Open-source contributor submits a change · 7 Security researcher reports a vulnerability · 8 Company deploys automatically from GitHub · 9 Developer accidentally deletes work · 10 Secret accidentally pushed (fake token only) · 11 Team hits a merge conflict · 12 Project needs a release.", "",
 "## Exercise levels (every chapter)", "L1 Guided · L2 Partially guided · L3 Independent · L4 Professional scenario · L5 Troubleshooting. Solutions separate.", "",
 f"## Final Mastery Assessment ({n('assessment')})",
 "Practical, not multiple-choice. Six practical tasks + one troubleshooting lab + one written design memo, scored on a rubric (Not yet / Developing / Proficient / Expert) with observable criteria. Areas: concepts, commands, troubleshooting, branches, collaboration, GitHub repository management, pull requests, code review, Actions, security, releases, deployment, open-source contribution. Instructor key and rubric are separate.", "",
 "## Safety rules for exercises", "- Fake secrets only (e.g. `FAKE_TOKEN_DO_NOT_USE_0000`); never a real credential.", "- All exercises run in the sandbox folder; destructive commands only on sandbox repositories.", "- Exercises that need a GitHub account state that clearly, and offer a local bare-repository alternative wherever the concept allows."]
w("05-project-plan.md", "\n".join(L) + "\n")
print("built:", len(T.C), "chapters")

# ---------- 13 gap resolution (the 23 gaps from 10-architecture-review.md)
G = [
 (1,"Plain text, encodings, newlines","text","Resolved: new chapter"),
 (2,"PATH / environment variables","terminal","Resolved: covered in shell chapter; revisited at install"),
 (3,"Shell differences","terminal","Resolved: shells + Git Bash strategy; Appendix M"),
 (4,"Downloading, zips, installers, admin rights, package managers","computer","Resolved: expanded scope of chapter 1"),
 (5,"Cloud sync vs version control","problem","Resolved: added to chapter scope"),
 (6,"Markdown","markdown","Resolved: new chapter, before any README work"),
 (7,"Bare repository as local remote","remotes","Resolved: remotes chapter opens with it"),
 (8,"Configuration scopes and includes","config","Resolved: dedicated chapter"),
 (9,"Object inspection commands (ls-files, show-ref, fsck, archive)","objects","Resolved: added to chapter scope"),
 (10,"Secret-removal tooling in history","gitsec","Resolved in scope; specific tools BLOCKED on official-doc verification (ledger)"),
 (11,"Reading official documentation","readdocs","Resolved: new chapter"),
 (12,"Notifications, stars, watching","notify","Resolved: new chapter; GitHub facts unverified"),
 (13,"Markdown on GitHub / README rendering","readme","Resolved in scope; rendering details unverified"),
 (14,"Wiki, Deployments/Environments, Settings, Security tab","settings","Resolved: new chapter; UI unverified"),
 (15,"Expressions/contexts, concurrency, self-hosted runners, debugging","exprs","Resolved: chapters for expressions, debugging and runners/limits"),
 (16,"Actions billing and limits","runners","Resolved in scope; numbers BLOCKED (omit unless verified)"),
 (17,"Merge queue / auto-merge","pr","Open: mention only if verified"),
 (18,"Repository templates, Gists","ghrepo","Open: decide after GitHub research"),
 (19,"Size risk; one book","(book-wide)","Resolved: Core/Deep tags and First-Read Path"),
 (20,"Appendices A-L enumerated","(back matter)","Resolved: A-L plus M (shell equivalence) and N (sources/verification log)"),
 (21,"Exercises/solutions/diagrams folders","(repo)","Resolved: folders and registry created"),
 (22,"Security spread across chapters","gitsec","Resolved: Security-note callout convention + Appendix G; chapters at " ),
 (23,"Forward references","model","Managed: see dependency map risk list"),
]
L = ["# 13 — Resolution of the 23 Architecture Gaps (generated)", "", "| # | Gap | Where it lives now | Status |", "|---|---|---|---|"]
for g in G:
    where = n(g[2]) + " " + title(g[2]) if g[2] in num else g[2]
    note = g[3] + (", ".join(n(k) for k in ("tracking", "gitsec", "ghauth", "wfsec", "ghsec", "secpractice")) if g[0] == 22 else "")
    L.append(f"| {g[0]} | {g[1]} | {where} | {note} |")
L += ["", "Open items (17, 18) and all 'unverified' notes are tracked in `research/research-ledger.csv`."]
w("13-gap-resolution.md", "\n".join(L) + "\n")
print("gap file built")
